language: sh # Halcyon will handle all Haskell dependencies

before_install:
  - sudo mkdir -p /app
  - sudo chown $USER /app
  - git clone https://github.com/mietek/halcyon.git /app/halcyon

install:
  - /app/halcyon/halcyon build
  - /app/halcyon/halcyon paths > halcyon-env
  - /app/halcyon/halcyon install alex-3.1.4 --prefix=/app/sandbox
  - /app/halcyon/halcyon install happy-1.19.5 --prefix=/app/sandbox

script:
  - cd runtime; ant
  - cd .. && source halcyon-env && ./select-cabal.sh && cabal sandbox init && ln -sf /app/sandbox/cabal.sandbox.config cabal.sandbox.config && cabal install
