language: sh # Halcyon will handle all Haskell dependencies

before_install:
  - sudo mkdir -p /app
  - sudo chown $USER /app
  - git clone https://github.com/mietek/halcyon.git /app/halcyon

install:
  - /app/halcyon/halcyon build
  - /app/halcyon/halcyon paths > halcyon-env
  - ln -sf /app/sandbox/cabal.sandbox.config cabal.sandbox.config

script:
  - cd runtime; ant
  - ./select-cabal.sh
  - source halcyon-env && cabal configure --enable-tests && cabal test
